# # DPC++ ---> data parallel C++
# ''' 
# DPC++ ---> DATA PARALLEL C++
# GUDIO VAN ROSSUM IN 1969

# ''' 

# # -*- coding: utf-8 -*-
# """31_Oct_Workshop_Python.ipynb

# Automatically generated by Colaboratory.

# Original file is located at
#     https://colab.research.google.com/drive/1Fkh6fA5mLfoeNhwZxfHoaYRGYZjTA0nL
# """

# month=2023
# print(type(month))

# a=5.67
# type(a)

# bool=True
# type(False)

# string = 'Python "String" '
# print(string)

# my_str="PYTHON ROCKS"
# print(my_str)
# print(len(my_str))
# print(my_str[10])
# print(my_str[-11])
# print(my_str[-1])
# print(my_str[0:7])
# print(my_str[-12:-1])
# print(my_str[-12:])

# mytup1=(12,25.4,'python',212)
# mytup2=(-21,224,87.6,'hello',22)
# print(mytup1)
# print(len(mytup1))
# print(type(mytup1))
# print(mytup2)
# print(len(mytup2))
# print(type(mytup2))

# tup=()
# print(type(tup))

# emptup=()
# print(type(emptup))
# print(emptup)
# onetup=(212,)
# print(type(onetup))
# print(onetup)
# onetup1=(212.5)
# print(type(onetup1))
# print(onetup1)

# tup=(1,"a",1.00000000001,True,[2,5,'keshav'])
# print(type(tup))
# print(len(tup))
# l=list(tup)
# l.append(45)
# t=tuple(l)
# print(t)

# tup=("keshav",1,5,8)
# print(type(tup))
# a=list(tup)
# a.remove("keshav")
# #a.insert("krishnam",4)
# tup=tuple(a)
# print(tup)

# # Hello ! This is a python program



